services:
  api:
    build: .
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"

  streamlit:
    environment:
      API_URL: http://api:8000 
    build: .
    command: streamlit run streamlit.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - api
